version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/dev.db
      - PORT=3001
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development services
  app-dev:
    build:
      context: .
      target: builder
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/dev.db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
      - ./data:/app/data
      - ./uploads:/app/uploads
    command: npm run dev
    profiles:
      - dev